/*
 * Copyright 2015 Freescale Semiconductor, Inc. All Rights Reserved.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 */

#ifndef __ASM_ARCH_D4400_QSPI_D4400_H__
#define __ASM_ARCH_D4400_QSPI_D4400_H__


/* Check qspi flash type:
 *  QSPI_FLASH_TYPE_WINBOND - Winbond
 *  QSPI_FLASH_TYPE_SPANSION- Spansion
 *  QSPI_FLASH_TYPE_MACRONIX- Macronix
 *  QSPI_FLASH_TYPE_NUMONYX - Numonyx
 */
#define QSPI_FLASH_TYPE_WINBOND		0
#define QSPI_FLASH_TYPE_SPANSION	1
#define QSPI_FLASH_TYPE_MACRONIX	2
#define QSPI_FLASH_TYPE_NUMONYX		3

/*
 *  QSPI register definitions
 */
/* Registers expressed in offsets and accessed via iomap.
 * Base address set in DTS file.
 */
#define QSPI_BASE_ADDR			0

#define QSPI_MCR_REG			(QSPI_BASE_ADDR + 0x000)
#define QSPI_LCR_REG			(QSPI_BASE_ADDR + 0x004)
#define QSPI_SFAR_REG			(QSPI_BASE_ADDR + 0x100)
#define QSPI_ICR_REG			(QSPI_BASE_ADDR + 0x104)
#define QSPI_SMPR_REG			(QSPI_BASE_ADDR + 0x108)
#define QSPI_RBSR_REG			(QSPI_BASE_ADDR + 0x10C)
#define QSPI_RBCT_REG			(QSPI_BASE_ADDR + 0x110)
#define QSPI_TBSR_REG			(QSPI_BASE_ADDR + 0x150)
/* AFD4400 rev1 has 16 32-bit deep TX buffer */
#define QSPI_TBDR_REG			(QSPI_BASE_ADDR + 0x154)
#define QSPI_ACR_REG			(QSPI_BASE_ADDR + 0x158)
#define QSPI_SR_REG			(QSPI_BASE_ADDR + 0x15C)
#define QSPI_FR_REG			(QSPI_BASE_ADDR + 0x160)
#define QSPI_RSER_REG			(QSPI_BASE_ADDR + 0x164)
#define QSPI_RXDATA_BASE_REG		(QSPI_BASE_ADDR + 0x200)
#define QSPI_RXDATA_RBDR0		(QSPI_BASE_ADDR + 0x200)
#define QSPI_RXDATA_RBDR1		(QSPI_BASE_ADDR + 0x204)
#define QSPI_RXDATA_RBDR2		(QSPI_BASE_ADDR + 0x208)
#define QSPI_RXDATA_RBDR3		(QSPI_BASE_ADDR + 0x20C)
#define QSPI_RXDATA_RBDR4		(QSPI_BASE_ADDR + 0x210)
#define QSPI_RXDATA_RBDR5		(QSPI_BASE_ADDR + 0x214)
#define QSPI_RXDATA_RBDR6		(QSPI_BASE_ADDR + 0x218)
#define QSPI_RXDATA_RBDR7		(QSPI_BASE_ADDR + 0x21C)
#define QSPI_RXDATA_RBDR8		(QSPI_BASE_ADDR + 0x220)
#define QSPI_RXDATA_RBDR9		(QSPI_BASE_ADDR + 0x224)
#define QSPI_RXDATA_RBDR10		(QSPI_BASE_ADDR + 0x228)
#define QSPI_RXDATA_RBDR11		(QSPI_BASE_ADDR + 0x22C)
#define QSPI_RXDATA_RBDR12		(QSPI_BASE_ADDR + 0x230)
#define QSPI_RXDATA_RBDR13		(QSPI_BASE_ADDR + 0x234)
#define QSPI_RXDATA_RBDR14		(QSPI_BASE_ADDR + 0x238)
#define QSPI_RXDATA_RBDR15		(QSPI_BASE_ADDR + 0x23C)
#define QSPI_RXDATA_RBDR16		(QSPI_BASE_ADDR + 0x240)
#define QSPI_RXDATA_RBDR17		(QSPI_BASE_ADDR + 0x244)
#define QSPI_RXDATA_RBDR18		(QSPI_BASE_ADDR + 0x248)
#define QSPI_RXDATA_RBDR19		(QSPI_BASE_ADDR + 0x24C)
#define QSPI_RXDATA_RBDR20		(QSPI_BASE_ADDR + 0x250)
#define QSPI_RXDATA_RBDR21		(QSPI_BASE_ADDR + 0x254)
#define QSPI_RXDATA_RBDR22		(QSPI_BASE_ADDR + 0x258)
#define QSPI_RXDATA_RBDR23		(QSPI_BASE_ADDR + 0x25C)
#define QSPI_RXDATA_RBDR24		(QSPI_BASE_ADDR + 0x260)
#define QSPI_RXDATA_RBDR25		(QSPI_BASE_ADDR + 0x264)
#define QSPI_RXDATA_RBDR26		(QSPI_BASE_ADDR + 0x268)
#define QSPI_RXDATA_RBDR27		(QSPI_BASE_ADDR + 0x26C)
#define QSPI_RXDATA_RBDR28		(QSPI_BASE_ADDR + 0x270)
#define QSPI_RXDATA_RBDR29		(QSPI_BASE_ADDR + 0x274)
#define QSPI_RXDATA_RBDR30		(QSPI_BASE_ADDR + 0x278)
#define QSPI_RXDATA_RBDR31		(QSPI_BASE_ADDR + 0x27C)

#define QSPI_MCR_EXT_ADD_OFFSET		0
#define QSPI_MCR_EXT_ADD_MASK		(1 << QSPI_MCR_EXT_ADD_OFFSET)
#define QSPI_MCR_VMID_OFFSET		3
#define QSPI_MCR_VMID_MASK		(0xF << QSPI_MCR_VMID_OFFSET)
#define QSPI_MCR_CLR_RXF_OFFSET		10
#define QSPI_MCR_CLR_RXF_MASK		(1 << QSPI_MCR_CLR_RXF_OFFSET)
#define QSPI_MCR_CLR_TXF_OFFSET		11
#define QSPI_MCR_CLR_TXF_MASK		(1 << QSPI_MCR_CLR_TXF_OFFSET)
#define QSPI_MCR_MDIS_OFFSET		14
#define QSPI_MCR_MDIS_MASK		(1 << QSPI_MCR_MDIS_OFFSET)
#define QSPI_MCR_ISD2FA_OFFSET		16
#define QSPI_MCR_ISD2FA_MASK		(1 << QSPI_MCR_ISD2FA_OFFSET)
#define QSPI_MCR_ISD3FA_OFFSET		17
#define QSPI_MCR_ISD3FA_MASK		(1 << QSPI_MCR_ISD3FA_OFFSET)
#define QSPI_MCR_ISD2FB_OFFSET		18
#define QSPI_MCR_ISD2FB_MASK		(1 << QSPI_MCR_ISD2FB_OFFSET)
#define QSPI_MCR_ISD3FB_OFFSET		19
#define QSPI_MCR_ISD3FB_MASK		(1 << QSPI_MCR_ISD3FB_OFFSET)
#define QSPI_MCR_SCLKCFG_OFFSET		24
#define QSPI_MCR_SCLKCFG_MASK		(0xFF << QSPI_MCR_SCLKCFG_OFFSET)

#define QSPI_ICR_IC_OFFSET		0
/* Errata in AFD4400 ref manual, ICO ofset is 16 (not 8). */
#define QSPI_ICR_ICO_OFFSET		16

#define QSPI_TBSR_TRBFL_OFFSET		8
#define QSPI_TBSR_TRBFL_MASK		(0x0F << QSPI_TBSR_TRBFL_OFFSET)
#define QSPI_TBSR_TRCTR_OFFSET		16
#define QSPI_TBSR_TRCTR_MASK		(0xFF << QSPI_TBSR_TRCTR_OFFSET)

#define QSPI_SMPR_HSENA_OFFSET		0
#define QSPI_SMPR_HSENA_MASK		(1 << QSPI_SMPR_HSENA_OFFSET)
#define QSPI_SMPR_HSPHS_OFFSET		1
#define QSPI_SMPR_HSPHS_MASK		(1 << QSPI_SMPR_HSDLY_OFFSET)
#define QSPI_SMPR_HSDLY_OFFSET		2
#define QSPI_SMPR_HSDLY_MASK		(1 << QSPI_SMPR_HSDLY_OFFSET)
#define QSPI_SMPR_FSPHS_OFFSET		5
#define QSPI_SMPR_FSPHS_MASK		(1 << QSPI_SMPR_FSPHS_OFFSET)
#define QSPI_SMPR_FSDLY_OFFSET		6
#define QSPI_SMPR_FSDLY_MASK		(1 << QSPI_SMPR_FSDLY_OFFSET)

#define QSPI_SR_BUSY_OFFSET		0
#define QSPI_SR_BUSY_MASK		(1 << QSPI_SR_BUSY_OFFSET)
#define QSPI_SR_IP_ACC_OFFSET		1
#define QSPI_SR_IP_ACC_MASK		(1 << QSPI_SR_IP_ACC_OFFSET)
#define QSPI_SR_AHB_ACC_OFFSET		2
#define QSPI_SR_AHB_ACC_MASK		(1 << QSPI_SR_AHB_ACC_OFFSET)
#define QSPI_SR_CNTMDFA_OFFSET		3
#define QSPI_SR_CNTMDFA_MASK		(1 << QSPI_SR_CNTMDFA_OFFSET)
#define QSPI_SR_AHBGNT_OFFSET		5
#define QSPI_SR_AHBGNT_MASK		(1 << QSPI_SR_AHBGNT_OFFSET)
#define QSPI_SR_AHBTRN_OFFSET		6
#define QSPI_SR_AHBTRN_MASK		(1 << QSPI_SR_AHBTRN_OFFSET)
#define QSPI_SR_AHBNE_OFFSET		8
#define QSPI_SR_AHBNE_MASK		(1 << QSPI_SR_AHBNE_OFFSET)
#define QSPI_SR_AHBFULL_OFFSET		11
#define QSPI_SR_AHBFULL_MASK		(1 << QSPI_SR_AHBFULL_OFFSET)
#define QSPI_SR_RXWE_OFFSET		16
#define QSPI_SR_RXWE_MASK		(1 << QSPI_SR_RXWE_OFFSET)
#define QSPI_SR_RXFULL_OFFSET		19
#define QSPI_SR_RXFULL_MASK		(1 << QSPI_SR_RXFULL_OFFSET)
#define QSPI_SR_RXDMA_OFFSET		23
#define QSPI_SR_RXDMA_MASK		(1 << QSPI_SR_RXDMA_OFFSET)
#define QSPI_SR_TXNE_OFFSET		24
#define QSPI_SR_TXNE_MASK		(1 << QSPI_SR_TXNE_OFFSET)
#define QSPI_SR_TXFULL_OFFSET		27
#define QSPI_SR_TXFULL_MASK		(1 << QSPI_SR_TXFULL_OFFSET)

#define QSPI_RBCT_RXBRD_OFFSET		8
#define QSPI_RBCT_RXBRD_MASK		(1 << QSPI_RBCT_RXBRD_OFFSET)
#define QSPI_RBCT_RXBRD_USEIPS		(0x1 << QSPI_RBCT_RXBRD_OFFSET)
#define QSPI_RBCT_WMRK_OFFSET		0
#define QSPI_RBCT_WMRK_MASK		(0x1F << QSPI_RBCT_WMRK_OFFSET)

#define QSPI_FR_TFF_OFFSET		0
#define QSPI_FR_TFF_MASK		(1 << QSPI_FR_TFF_OFFSET)
#define QSPI_FR_IPGEF_OFFSET		4
#define QSPI_FR_IPGEF_MASK		(1 << QSPI_FR_IPGEF_OFFSET)
#define QSPI_FR_IPIEF_OFFSET		6
#define QSPI_FR_IPIEF_MASK		(1 << QSPI_FR_IPIEF_OFFSET)
#define QSPI_FR_IPAEF_OFFSET		7
#define QSPI_FR_IPAEF_MASK		(1 << QSPI_FR_IPAEF_OFFSET)
#define QSPI_FR_IMEF_OFFSET		9
#define QSPI_FR_IMEF_MASK		(1 << QSPI_FR_IMEF_OFFSET)
#define QSPI_FR_ICEF_OFFSET		10
#define QSPI_FR_ICEF_MASK		(1 << QSPI_FR_ICEF_OFFSET)
#define QSPI_FR_IUEF_OFFSET		11
#define QSPI_FR_IUEF_MASK		(1 << QSPI_FR_IUEF_OFFSET)
#define QSPI_FR_ABOF_OFFSET		12
#define QSPI_FR_ABOF_MASK		(1 << QSPI_FR_ABOF_OFFSET)
#define QSPI_FR_ABMEF_OFFSET		13
#define QSPI_FR_ABMEF_MASK		(1 << QSPI_FR_ABMEF_OFFSET)
#define QSPI_FR_ABCEF_OFFSET		14
#define QSPI_FR_ABCEF_MASK		(1 << QSPI_FR_ABCEF_OFFSET)
#define QSPI_FR_RBDF_OFFSET		16
#define QSPI_FR_RBDF_MASK		(1 << QSPI_FR_RBDF_OFFSET)
#define QSPI_FR_RBOF_OFFSET		17
#define QSPI_FR_RBOF_MASK		(1 << QSPI_FR_RBOF_OFFSET)
#define QSPI_FR_TBUF_OFFSET		26
#define QSPI_FR_TBUF_MASK		(1 << QSPI_FR_TBUF_OFFSET)
#define QSPI_FR_TBFF_OFFSET		27
#define QSPI_FR_TBFF_MASK		(1 << QSPI_FR_TBFF_OFFSET)

#define QSPI_RSER_TFIE_OFFSET		0
#define QSPI_RSER_TFIE_MASK		(1 << QSPI_RSER_TFIE_OFFSET)
#define QSPI_RSER_IPGEIE_OFFSET		4
#define QSPI_RSER_IPGEIE_MASK		(1 << QSPI_RSER_IPGEIE_OFFSET)
#define QSPI_RSER_IPIEIE_OFFSET		6
#define QSPI_RSER_IPIEIE_MASK		(1 << QSPI_RSER_IPIEIE_OFFSET)
#define QSPI_RSER_IPAEIE_OFFSET		7
#define QSPI_RSER_IPAEIE_MASK		(1 << QSPI_RSER_IPAEIE_OFFSET)
#define QSPI_RSER_IMEIE_OFFSET		9
#define QSPI_RSER_IMEIE_MASK		(1 << QSPI_RSER_IMEIE_OFFSET)
#define QSPI_RSER_ICEIE_OFFSET		10
#define QSPI_RSER_ICEIE_MASK		(1 << QSPI_RSER_ICEIE_OFFSET)
#define QSPI_RSER_IUEIE_OFFSET		11
#define QSPI_RSER_IUEIE_MASK		(1 << QSPI_RSER_IUEIE_OFFSET)
#define QSPI_RSER_ABOIE_OFFSET		12
#define QSPI_RSER_ABOIE_MASK		(1 << QSPI_RSER_ABOIE_OFFSET)
#define QSPI_RSER_ABMEIE_OFFSET		13
#define QSPI_RSER_ABMEIE_MASK		(1 << QSPI_RSER_ABMEIE_OFFSET)
#define QSPI_RSER_ABCEIE_OFFSET		14
#define QSPI_RSER_ABCEIE_MASK		(1 << QSPI_RSER_ABCEIE_OFFSET)
#define QSPI_RSER_RBDIE_OFFSET		16
#define QSPI_RSER_RBDIE_MASK		(1 << QSPI_RSER_RBDIE_OFFSET)
#define QSPI_RSER_RBOIE_OFFSET		17
#define QSPI_RSER_RBOIE_MASK		(1 << QSPI_RSER_RBOIE_OFFSET)
#define QSPI_RSER_RBDDE_OFFSET		21
#define QSPI_RSER_RBDDE_MASK		(1 << QSPI_RSER_RBDDE_OFFSET)
#define QSPI_RSER_TBUIE_OFFSET		26
#define QSPI_RSER_TBUIE_MASK		(1 << QSPI_RSER_TBUIE_OFFSET)
#define QSPI_RSER_TBFIE_OFFSET		27
#define QSPI_RSER_TBFIE_MASK		(1 << QSPI_RSER_TBFIE_OFFSET)

#define	QSPI_MAX_TX_BYTES		64	/* 16 32-bit words */
#define QSPI_MAX_RX_BYTES		128	/* 32 32-bit words */

/* Addressing mode
 * addr_mode: QSPI_ADDR_MODE_24BIT-24bit, QSPI_ADDR_MODE_32BIT-32bit
 */
#define QSPI_ADDR_MODE_24BIT	0
#define QSPI_ADDR_MODE_32BIT	1

#endif
